services:
  backend:
    build: ./backend
    container_name: mpc-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
      - ./backend/temp_protocols:/app/temp_protocols
      - ./backend/models_cache:/app/models_cache
      - ./backend/storage:/app/storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    depends_on:
      - ollama
    networks:
      - mpc-network

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ollama:
    image: ollama/ollama:latest
    container_name: mpc-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    restart: always
    networks:
      mpc-network:
        aliases:
          - ollama

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build: ./frontend
    container_name: mpc-frontend
    ports:
      - "90:80"
    depends_on:
      - backend
    restart: always
    networks:
      - mpc-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mpc-network:
    driver: bridge
